services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    labels:
      glance.name: Portainer
      glance.icon: di:portainer
      glance.url: https://jeancloud:9443
      glance.description: Docker Management
      glance.category: system
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERCONFDIR}/portainer:/data
    ports:
      - "9000:9000"
      - "9443:9443"